1. Articles table view shows one cell per category; the cell contains…
AlexRamey/mbird-iOS pull request #22
Opened 2017-12-06 03:17 UTC by AlexRamey

… a collection view of horizontally scrolling articles from that category

2017-12-07 02:20 UTC, jdwitten requested changes
looks good, just a few comments

2017-12-07 02:20 UTC, jdwitten commented on iOS Client/ArticlesController/TableViewCell/ArticleTableViewCell.swift
> +        if itemCount == 1 {
nice, I like it make the article big if there is only one

2017-12-07 02:20 UTC, jdwitten commented on iOS Client/ArticlesController/TableViewCell/ArticleTableViewCell.swift
> +    func configure(articles: [MBArticle]) {
I like the collection view inside of the table view cell. Only thing I'm thinking from a UX experience it might be difficult to see only the most recent articles. Maybe have a section that is just new articles? No actionable suggestions just something we should think about

2017-12-07 02:20 UTC, jdwitten commented on iOS Client/ArticlesController/CollectionViewCell/ArticleItem.swift
> +    func configure(article: MBArticle) {
could be cool to throw in some rounded corners or something snazzy on these images. Don't have to do it for this PR

2017-12-07 02:20 UTC, jdwitten commented on iOS Client/ArticlesController/MBArticlesViewController.swift
>                  for topLevelCategory in topLevelCategories {
Do we need to do this second for loop here? I'm thinking we are already looping through categories in the flatMap above, so instead of creating that Set and instead of returning, just insert the category into retVal and update its corresponding array. Let me know if that makes sense or if I'm missing something

2017-12-07 02:20 UTC, jdwitten commented on iOS Client/ArticlesController/MBArticlesViewController.swift
> +        // sort newest articles first
Learned about something cool today called Date.distantPast that I think we could use here to make this loop a little more succinct maybe something like:
`
retVal.keys.forEach {
    retVal[$0] = retVal[$0]?.sorted { a1, a2 in
        return (a1 .date as? Date ?? Date.distantPast) > (a2.date as? Date ?? Date.distantPast)
    }
}
`

2017-12-07 02:20 UTC, jdwitten commented on iOS Client/ArticlesController/MBArticlesViewController.swift
> +        // sort newest articles first
whoops the formatting turned out bad on that ^

2017-12-07 02:20 UTC, jdwitten commented on iOS Client/ArticlesController/MBArticlesViewController.swift
> +    let reuseIdentifier = "ArticleCellReuseIdentifier"
nice

2017-12-07 02:27 UTC, AlexRamey commented on iOS Client/ArticlesController/CollectionViewCell/ArticleItem.swift
> +    func configure(article: MBArticle) {
agreed, we need to make this as fancy as possible. sounds like a good follow-up.

2017-12-07 02:31 UTC, AlexRamey commented on iOS Client/ArticlesController/TableViewCell/ArticleTableViewCell.swift
> +    func configure(articles: [MBArticle]) {
yeah, the website somehow has featured articles but I don't see that exposed to us in the API. Would be great to get a featured section or New Content section or something. Let's discuss this on Friday. For now, I am sorting the newest articles first so the user should at least see for each section

2017-12-07 02:35 UTC, AlexRamey commented on iOS Client/ArticlesController/MBArticlesViewController.swift
> +        // sort newest articles first
I like that; this felt very clunky to me when I was writing it.

2017-12-07 03:01 UTC, jdwitten submitted a review, later dismissed
Don't know if you saw my other comment about having two loops when building out the categories, but I think it's something to look at for a future refactor. I'll approve now but let's revisit

2017-12-07 03:38 UTC, AlexRamey commented on iOS Client/ArticlesController/MBArticlesViewController.swift
> +        // sort newest articles first
addressed.

2017-12-07 03:41 UTC, AlexRamey commented on iOS Client/ArticlesController/MBArticlesViewController.swift
>                  for topLevelCategory in topLevelCategories {
I cleaned this up a bit. I couldn't see a way to get rid of the two loops b/c I needed to create a set before continuing to remove potential duplicates.

I moved these details into a helper on article called `getTopLevelCategories` that just returns a set. So we just iterate over that set directly here now

2017-12-08 02:38 UTC, jdwitten approved these changes
Looks good my dude much better

2017-12-08 03:23 UTC, merged